export const categories = [
  {
    id: 1,
    name: "Pizza",
    //image: require("../assets/images/"),
  },
  {
    id: 2,
    name: "Burger",
    //image: require("../assets/images/"),
  },
  {
    id: 3,
    name: "Chinese",
    //image: require("../assets/images/"),
  },
  {
    id: 4,
    name: "Noodles",
    //image: require("../assets/images/"),
  },
  {
    id: 5,
    name: "Italian",
    //image: require("../assets/images/"),
  },

  {
    id: 6,
    name: "Sweets",
    //image: require("../assets/images/"),
  },
];

export const feaured = {
  id: 1,
  title: "Hot and Spicy",
  description: "soft and tender fried chicken",
  restaurants: [
    {
      id: 1,
      name: "Bella Kay",
      image: require("../assets/images/6776_Pizza-Dough_ddmfs_2x1_1725-fdaa76496da045b3bdaadcec6d4c5398.jpg"),
      description: "Hot and Spicy Pizza",
      lng: 38.2145602,
      lat: -85.5324269,
      address: "434 first East Cross",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Pizza",
          description: "Cheezy garlic pizza",
          price: "10",
          //image: require("../assets/images/"),
        },
        {
          id: 2,
          name: "Pizza",
          description: "Cheezy garlic pizza",
          price: "10",
          image: require("../assets/images/6776_Pizza-Dough_ddmfs_2x1_1725-fdaa76496da045b3bdaadcec6d4c5398.jpg"),
        },
        {
          id: 3,
          name: "Pizza",
          description: "Cheezy garlic pizza",
          price: "10",
          image: require("../assets/images/6776_Pizza-Dough_ddmfs_2x1_1725-fdaa76496da045b3bdaadcec6d4c5398.jpg"),
        },
      ],
    },
    {
      id: 2,
      name: "Bella Kay",
      image: require("../assets/images/6776_Pizza-Dough_ddmfs_2x1_1725-fdaa76496da045b3bdaadcec6d4c5398.jpg"),
      description: "Hot and Spicy Pizza",
      lng: 38.2145602,
      lat: -85.5324269,
      address: "434 first East Cross",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Pizza",
          description: "Cheezy garlic pizza",
          price: "10",
          //image: require("../assets/images/"),
        },
        {
          id: 2,
          name: "Pizza",
          description: "Cheezy garlic pizza",
          price: "10",
          image: require("../assets/images/6776_Pizza-Dough_ddmfs_2x1_1725-fdaa76496da045b3bdaadcec6d4c5398.jpg"),
        },
        {
          id: 3,
          name: "Pizza",
          description: "Cheezy garlic pizza",
          price: "10",
          image: require("../assets/images/6776_Pizza-Dough_ddmfs_2x1_1725-fdaa76496da045b3bdaadcec6d4c5398.jpg"),
        },
      ],
    },
    {
      id: 3,
      name: "Bella Kay",
      image: require("../assets/images/6776_Pizza-Dough_ddmfs_2x1_1725-fdaa76496da045b3bdaadcec6d4c5398.jpg"),
      description: "Hot and Spicy Pizza",
      lng: 38.2145602,
      lat: -85.5324269,
      address: "434 first East Cross",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "Pizza",
          description: "Cheezy garlic pizza",
          price: "10",
          image: require("../assets/images/6776_Pizza-Dough_ddmfs_2x1_1725-fdaa76496da045b3bdaadcec6d4c5398.jpg"),
        },
        {
          id: 2,
          name: "Pizza",
          description: "Cheezy garlic pizza",
          price: "10",
          image: require("../assets/images/6776_Pizza-Dough_ddmfs_2x1_1725-fdaa76496da045b3bdaadcec6d4c5398.jpg"),
        },
        {
          id: 3,
          name: "Pizza",
          description: "Cheezy garlic pizza",
          price: "10",
          image: require("../assets/images/6776_Pizza-Dough_ddmfs_2x1_1725-fdaa76496da045b3bdaadcec6d4c5398.jpg"),
        },
      ],
    },
  ],
};
